name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - output

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: output

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: Pankitgg
          output_file: github-contribution-grid-snake.svg
          commits_snake: false
          palette: github
          snake_color_mode: "fixed"
          snake_color: "#f0883e"
          bg_color: "#0d1117"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update snake animation"